name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  create:
    tags:
      - v*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Login to GitHub Container Registry
      uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        tag="${GITHUB_REF##*/}"
        image_name="ghcr.io/pschichtel/kata-kernel:${tag}"
        docker build --cache-from type=gha --cache-to type=gha,mode=max -t "$image_name" .
        docker push "$image_name"

