name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  create:
    tags:
      - v*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        tag="${GITHUB_REF##*/}"
        image_name="ghcr.io/pschichtel/kata-kernel:${tag}"
        docker build --cache-from type=gha --cache-to type=gha,mode=max -t "$image_name" .
        docker push "$image_name"

